eslint:
  enabled: true
  config_file: .eslintrc

jshint:
  enabled: false

ruby:
  enabled: true
  config_file: .rubocop.yml

sass-lint:
  enabled: true
  config_file: .sass-lint.yml

scss:
  enabled: false
