AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - "**/*.slim"
    - "vendor/**/*"
    - "db/schema.rb"

Lint/EndAlignment:
  EnforcedStyleAlignWith: variable

Metrics/LineLength:
  Max: 90
  Exclude:
    - "**/*.jbuilder"

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/AlignArray:
  Enabled: false

Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Style/AsciiComments:
  Enabled: false

Style/CaseIndentation:
  EnforcedStyle: end

Style/Documentation:
  Enabled: false

Style/DotPosition:
  EnforcedStyle: trailing

Style/IndentArray:
  EnforcedStyle: consistent

Style/Lambda:
  Enabled: false

Style/MultilineOperationIndentation:
  EnforcedStyle: indented

Style/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Style/StringLiterals:
  EnforcedStyle: double_quotes
