exclude:
  - "vendor/assets/stylesheets/**"
linters:
  LeadingZero:
    style: exclude_zero
  NestingDepth:
    max_depth: 4
  SelectorFormat:
    convention: hyphenated_BEM
  StringQuotes:
    style: double_quotes
