exclude:
  - "vendor/assets/stylesheets/**"
linters:
  LeadingZero:
    style: include_zero
  NestingDepth:
    max_depth: 5
  SelectorDepth:
    max_depth: 5
  SelectorFormat:
    convention: hyphenated_BEM
  StringQuotes:
    style: single_quotes
