language: ruby

node_js:
  - "6"

addons:
  postgresql: "9.4"
  hosts:
    - annict.dev
    - api.annict.dev

cache:
  directories:
    - vendor/bundle
    - node_modules
  yarn: true

before_install:
  - export TZ=Asia/Tokyo
  - gem update --system

install:
  - bundle install --deployment --jobs=3 --retry=3
  - npm install

before_script:
  - bundle exec rake db:create
  - bundle exec rake db:migrate

script:
  - bundle exec rspec

notifications:
  email: false
  slack: annict:rn43dPpTg6KuZZajh4PK33r9

env:
  global:
    - ANNICT_BASIC_AUTH=off
    - ANNICT_CURRENT_SEASON=2017-winter
    - ANNICT_EN_URL=http://en.annict.dev
    - ANNICT_JA_URL=http://ja.annict.dev
    - ANNICT_NEXT_SEASON=2017-spring
    - ANNICT_PAPERCLIP_PATH="paperclip/:class/:id/:attachment/:style/:hash.:extension"
    - ANNICT_PAPERCLIP_URL=:rails_root/public/paperclip/:class/:id/:attachment/:style/:hash.:extension"
    - ANNICT_PREVIOUS_SEASON=2016-autumn
