language: ruby

addons:
  postgresql: "9.4"
  hosts:
    - annict.dev
    - db.annict.dev
    - forum.annict.dev
    - api.annict.dev

cache:
  directories:
    - vendor/bundle
    - node_modules

install:
  - bundle install --deployment --jobs=3 --retry=3
  - npm install

before_script:
  - bundle exec rake db:create
  - bundle exec rake db:migrate

script:
  - bundle exec rspec

notifications:
  email: false
  slack: annict:rn43dPpTg6KuZZajh4PK33r9
