language: ruby

addons:
  postgresql: "9.4"
  hosts:
    - annict.dev
    - db.annict.dev
    - forum.annict.dev
    - api.annict.dev

cache:
  directories:
    - vendor/bundle
    - node_modules

before_install:
  - export TZ=Asia/Tokyo
  - gem update --system

install:
  - bundle install --deployment --jobs=3 --retry=3
  - npm install

before_script:
  - bundle exec rake db:create
  - bundle exec rake db:migrate

script:
  - bundle exec rspec

notifications:
  email: false
  slack: annict:rn43dPpTg6KuZZajh4PK33r9

env:
  global:
    - ANNICT_CURRENT_SEASON=2016-autumn
    - ANNICT_PREVIOUS_SEASON=2016-summer
    - ANNICT_NEXT_SEASON=2017-winter
